export const metadata = {
  title: 'export-link',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>{ children }</body>
    </html>
  )
}
