import 'destyle.css';
import '@/styles/global.scss';
import { ReactNode, Suspense } from 'react';
import { StyledComponentsRegistry } from '@/app/styling/StyledComponentsRegistry';
import { HistoryProvider } from '@/contexts/HistoryContext';
import { AllPageLayout } from '@/components/layouts/AllPageLayout';
import { NavigationEvents } from '@/components/organisms/NavigationEvents';

export const metadata = {
  title: 'page-transition',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <HistoryProvider>
          <>
            <StyledComponentsRegistry>
              <AllPageLayout>{ children }</AllPageLayout>
            </StyledComponentsRegistry>
            <Suspense fallback={null}>
              <NavigationEvents />
            </Suspense>
          </>
        </HistoryProvider>
      </body>
    </html>
  )
}
